# Generated by Django 4.0.6 on 2022-08-03 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=1)])),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=1)])),
                ('course_number', models.IntegerField(unique=True)),
                ('group_number', models.IntegerField(unique=True)),
                ('teacher', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=1)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('first_day', models.CharField(choices=[('0', 'saturday'), ('1', 'sunday'), ('2', 'monday'), ('3', 'tuesday'), ('4', 'wednesday')], max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=1)])),
                ('second_day', models.CharField(choices=[('0', 'saturday'), ('1', 'sunday'), ('2', 'monday'), ('3', 'tuesday'), ('4', 'wednesday')], max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=1)])),
            ],
        ),
    ]
