# Generated by Django 4.0.6 on 2022-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_squashed_0013_alter_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
